// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3J3pyGw5NSHqbif8MtKtUs1eF7aHDdm8',
    appId: '1:21310800133:web:1683126722837fab1cb76c',
    messagingSenderId: '21310800133',
    projectId: 'ssit-56fe5',
    authDomain: 'ssit-56fe5.firebaseapp.com',
    storageBucket: 'ssit-56fe5.appspot.com',
    measurementId: 'G-7ME8NDF0BY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFGO-WlL7bZ098txlGilfC3OnquNBTVKw',
    appId: '1:21310800133:android:546fdcd72c9bfaa91cb76c',
    messagingSenderId: '21310800133',
    projectId: 'ssit-56fe5',
    storageBucket: 'ssit-56fe5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3HsqE6jYqB5ESJ_HihEd1rLEzuFemw_0',
    appId: '1:21310800133:ios:6753a0b344da16cf1cb76c',
    messagingSenderId: '21310800133',
    projectId: 'ssit-56fe5',
    storageBucket: 'ssit-56fe5.appspot.com',
    iosBundleId: 'com.ssit.ssitCollegeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3HsqE6jYqB5ESJ_HihEd1rLEzuFemw_0',
    appId: '1:21310800133:ios:6753a0b344da16cf1cb76c',
    messagingSenderId: '21310800133',
    projectId: 'ssit-56fe5',
    storageBucket: 'ssit-56fe5.appspot.com',
    iosBundleId: 'com.ssit.ssitCollegeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3J3pyGw5NSHqbif8MtKtUs1eF7aHDdm8',
    appId: '1:21310800133:web:60c8d59f01bca45f1cb76c',
    messagingSenderId: '21310800133',
    projectId: 'ssit-56fe5',
    authDomain: 'ssit-56fe5.firebaseapp.com',
    storageBucket: 'ssit-56fe5.appspot.com',
    measurementId: 'G-NNBNHZJYNN',
  );

}