import 'package:flutter/material.dart';
Color backgroundColor1 = const Color(0xffE9EAF7);
Color backgroundColor2 = const Color(0xffF4EEF2);
Color backgroundColor3 = const Color(0xffEBEBF2);
Color backgroundColor4 = const Color(0xffE3EDF5);
Color primaryColor = const Color(0xffD897FD);
Color textColor1 = const Color(0xff353047);
Color textColor2 = const Color(0xff6F6B7A);
Color buttonColor = const Color(0xffFD6B68);
Color textFieldColor = const Color(0xFF3A4750);
Color loginButtonColor = const Color(0xFF3A4750);
Color labelColor = const Color(0xFF7B8A9A);
Color backgroundColor = const Color(0xFFEEF1F6);
String googleimage = 'images/google.png';